# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
db_user: "{{ lookup('env', 'BOT_DB_USER') }}"
db_password: "{{ lookup('env', 'BOT_DB_PASSWORD') }}"
db_name: "{{ lookup('env', 'BOT_DB_NAME') }}"
db_max_connections: 1000
db_total_memory: 1
postgresql_version: "{{ lookup('env', 'BOT_POSTGRES_VERSION') }}"
postgresql_apt_key_id: "ACCC4CF8"
postgresql_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgresql_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main {{ postgresql_version }}"