# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
- name: clean build dir
  become_user: "{{ local_user }}"
  local_action:
    module: file
    path: "{{ build_dir }}"
    state: absent
