# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
