# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
- name: Update PostgreSQL config
  become_user: postgres
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/user.conf"
  notify:
    - restart postgresql

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes