# Generated by Django 2.2 on 2019-07-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190709_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='psid',
        ),
    ]
