# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Hleb Serafimovich <hleb.serafimovich@celadon.ae>

HOME = 'HOME'
BACK = 'BACK'
UNKNOWN = 'UNKNOWN'
GET_STARTED = 'GET_STARTED'
ORDER_TO_GO = 'ORDER_TO_GO'

SELECT_ITEM = 'SELECT_ITEM'
SELECT_FACILITY = 'SELECT_FACILITY'

ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER'
CHANGE_QUANTITY_ITEM = 'CHANGE_QUANTITY_ITEM'
QUANTITY_BUTTON = 'QUANTITY_BUTTON'

ADD_MORE_ITEMS = 'ADD_MORE_ITEMS'
REMOVE_ITEM = 'REMOVE_ITEM'
CANCEL_ORDER = 'CANCEL_ORDER'

MAIN_MENU = 'MAIN_MENU'
ITEM_MENU = 'ITEM_MENU'

USER_TAG = 'USER_MSG'

WEBHOOK_EVENT = 'WEBHOOK_EVENT_REFERENCE'

MINSK = 'MINSK'
