# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
- name: Install apt packages
  become: yes
  apt:
    name:
      - build-essential
      - python3-pip
      - python3-dev
      - nginx
      - virtualenv
    update_cache: true
    state: present
