# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
- name: Create build dir
  local_action:
    module: file
    path: "{{ build_dir }}"
    state: directory

- name: create env file
  become_user: "{{local_user }}"
  local_action:
    module: shell
    args: python3 scrap_env_vars.py

- name: Push env file
  copy:
    src: "{{ build_dir }}/{{ app_name }}.env"
    dest: /etc/environment

- name: Remove build dir
  become_user: "{{local_user }}"
  local_action:
    module: file
    path: "{{ build_dir }}"
    state: absent
