# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
- name: Populate service facts
  service_facts:

- name: stop app service
  service:
    name: "{{ app_name }}"
    state: stopped
  when: "'{{ app_name }}.service' in {{ ansible_facts.services }}"
