# Copyright (c) 2019 Celadon Development LLC, All rights reserved.
# Author Alexander Drozdov <alexander.drozdov@celadon.ae>

---
- name: Deploy bot
  hosts:
    - all
  remote_user: root
  roles:
    - postgres
    - django
    - nginx